App\Form\Model\UserDeleteModel:
  properties:
    plainPassword:
      - Symfony\Component\Security\Core\Validator\Constraints\UserPassword:
          message: 'user.password.wrong'

App\Entity\User:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: [ 'email' ]
        message: 'user.email.exists'
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: [ 'username' ]
        message: 'user.username.exists'

