App\Form\Model\UserDeleteModel:
  properties:
    plainPassword:
      - Symfony\Component\Security\Core\Validator\Constraints\UserPassword:
          message: 'Wrong value for your current password'
